server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      # ============================
      # ðŸš€ GLOBAL CORS CONFIG
      # ============================
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: preflight-cors
          uri: no://op
          predicates:
            - Path=/api/**
            - Method=OPTIONS
          filters:
            - SetStatus=200
        - id: auth-login
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/login

        - id: auth-verify-otp
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/verify-otp

        - id: auth-current-user
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/current-user

        - id: auth-profile-user
          uri: lb://user-service
          predicates:
            - Path=/api/auth/profile

        - id: user-register
          uri: lb://user-service
          predicates:
            - Path=/api/auth/register/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**

        - id: hamster-service
          uri: lb://hamster-service
          predicates:
            - Path=/api/hamsters/**

        - id: grooming-service
          uri: lb://grooming-service
          predicates:
            - Path=/api/services/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
